### ISSUE TITLE
Большой метод

### ISSUE THREAD

**Issue by antonkazakov** [nikomp/DogsAPI#11]
https://github.com/nikomp/DogsAPI/blob/b2afc79d7344ea6355e66f5e6468ff7e914268b4/app/src/main/java/com/example/dogsapi/MainActivity.kt#L38

Очень большой метод. Нарушается принцип единой ответственности, инициализируются лишние обьекты, ухудшается читаемость

**Comment by nikomp** [comment]
Инициализацию ретрофита вынес в init{...}
