### ISSUE TITLE
Инициализация списков

### ISSUE THREAD

**Issue by antonkazakov** [nikomp/DogsAPI#5]
https://github.com/nikomp/DogsAPI/blob/b2afc79d7344ea6355e66f5e6468ff7e914268b4/app/src/main/java/com/example/dogsapi/MainActivity.kt#L36

Лучше сразу инициализировать через emptyList() чтобы избегать потом проверок на нулл.

**Comment by nikomp** [comment]
Через emptyList() не получится т.к. это ListView, в любом случае переменная у меня нигде не используется, убрал ее
