### ISSUE TITLE
Deserializer 

### ISSUE THREAD

**Issue by antonkazakov** [nikomp/DogsAPI#7]
https://github.com/nikomp/DogsAPI/blob/b2afc79d7344ea6355e66f5e6468ff7e914268b4/app/src/main/java/com/example/dogsapi/MainActivity.kt#L80

Советую подключать десериализатор(gson/moshi)  чтобы вручную не разбирать обьекты

**Comment by nikomp** [comment]
GSON у меня подключен, но от сервера приходит просто Json строка, я не стал писать отдельный класс для объектов, которые приходят от сервера. Мне проще было распарсить Json
