### ISSUE TITLE
RecyclerView

### ISSUE THREAD

**Issue by antonkazakov** [nikomp/DogsAPI#8]
https://github.com/nikomp/DogsAPI/blob/b2afc79d7344ea6355e66f5e6468ff7e914268b4/app/src/main/java/com/example/dogsapi/MainActivity.kt#L101

ЛУчше брать ресайклер вью либо реализовывать свой вьюхолдер паттерн

**Comment by nikomp** [comment]
Для этого примера, ListView будет норм
