### ISSUE TITLE
Generics

### ISSUE THREAD

**Issue by antonkazakov** [nikomp/DogsAPI#9]
https://github.com/nikomp/DogsAPI/blob/b2afc79d7344ea6355e66f5e6468ff7e914268b4/app/src/main/java/com/example/dogsapi/MainActivity.kt#L107

Почему используется стар проджекшен? ты же знаешь какого типа у тебя айтемы

**Comment by nikomp** [comment]
Проблема была не с <*>, нужно было просто отметить параметры в Лямбда выражении как неиспользуемые "_"
